name: Secret Scan - Gitleaks
on: [push]
jobs:
  SecretScan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Secret Scan
      uses: zricethezav/gitleaks-action@master